# Generated by Django 5.2.6 on 2026-09-09 17:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('customer_id', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('currency', models.CharField(max_length=3)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(db_index=True, max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=18)),
                ('note', models.TextField(blank=True, null=True)),
                ('vendor_updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SyncCheckpoint',
            fields=[
                ('source', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('watermark', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger', models.CharField(default='scheduled', max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('interrupted', 'Interrupted')], db_index=True, default='queued', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('sources', models.JSONField(default=dict)),
                ('reconciled', models.PositiveIntegerField(default=0)),
                ('unresolved', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('external_invoice_id', models.CharField(db_index=True, max_length=100, null=True)),
                ('type', models.CharField(max_length=20)),
                ('method', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('vendor_updated_at', models.DateTimeField()),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounting.invoice')),
            ],
        ),
    ]
