# Generated by Django 5.2.6 on 2026-09-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(choices=[('USD', 'US dollar'), ('EUR', 'Euro'), ('GBP', 'British pound')], max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('USD', 'US dollar'), ('EUR', 'Euro'), ('GBP', 'British pound')], max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='method',
            field=models.CharField(choices=[('bank_transfer', 'Bank transfer'), ('card', 'Card'), ('cash', 'Cash'), ('cheque', 'Cheque')], max_length=30),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund'), ('fee', 'Fee')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('currency__in', ['USD', 'EUR', 'GBP'])), name='invoice_currency_valid'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('currency__in', ['USD', 'EUR', 'GBP'])), name='transaction_currency_valid'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('type__in', ['payment', 'refund', 'fee'])), name='transaction_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('method__in', ['bank_transfer', 'card', 'cash', 'cheque'])), name='transaction_method_valid'),
        ),
    ]
