# Generated by Django 5.2.6 on 2026-09-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_constrain_currency_and_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncrun',
            name='started_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['type', 'occurred_at'], name='transaction_type_occurred_idx'),
        ),
    ]
